### ISSUE TITLE
Save term to custom post type taxonomy

### ISSUE THREAD

**Issue by pablopaul** [pods-framework/pods-caldera-forms#6]
Hey guys, 

I have the following situation:

Used pods to setup a CPT "initiatives" and a custom taxonomy "regions".
Using caldera forms and pods caldera forms to output a form to add new "initiatives" submissions from frontend. In this form I auto populate (nice feature ;-)) a dropdown with the custom taxonomy terms "regions". In the pods form processor the custom taxonomy "regions" is not "available" as a target to map the according form field, how can I solve this?

Thanks

**Comment by dlincoln** [comment]
I believe you just need to edit the Pod for "initiatives" itself. Two options there:
- simply go to advanced options tab, scroll down, and select the taxonomy "regions". This will make the taxonomy appear on the post sidebar in the backend of WP, and be selectable by posts and from... (if "initiatives" is a Pods-extended CPT and not a native Pod, there is no "advanced options" tab, so in that case you'd extend the taxonomy field with Pods, go to the advanced options of the taxonomy and assign "initiatives" as a post the Taxonomy relates to as above).

- the other (arguably more useful) way: add relationship. If all you need is a picker, add a relationship to the "initiatives" pod to the "regions" taxonomy as a field. This puts it in the regular "more fields" list on the backend, rather than the sidebar, and operates internally to Pods (but not as a WP conventional taxonomy). You can set relationships at both ends to pick from taxonomy OR the pod, so this gives you a lot of flexibility.

**Comment by Shelob9** [comment]
I am closing this as invalid. If the Pod is a post type and the field is related to a taxonomy, then this shouldn't update the term association. That's not what a relation to a taxonomy does. If you want it to, do something like this: https://github.com/pods-framework/pods-code-library/blob/e0bd40874c4bb82238cf57d4eaf7701c0f086f78/example/hooks/actions/pods_api_post_save_pod_item_podname/examples/update_taxonomy.php

If you want to use a Caldera Form to update a taxonomy term association for a post you can do one of two things:
1) Resolve this issue: https://github.com/CalderaWP/caldera-custom-fields/issues/2 
2) Use the run action processor to set the association https://calderawp.com/downloads/caldera-forms-run-action/
